name: bidi
description: Implementation of the BIDI algorithm, as described in http://www.unicode.org/reports/tr9/tr9-17.html.
version: 1.0.0+2
repository: https://github.com/xclud/dart_bidi
homepage: http://pwa.ir

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.3.0